// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_itfz9TO4HOXe7L64zk5058atnUx7UQ',
    appId: '1:551111069993:web:96d88405332e229c9d6738',
    messagingSenderId: '551111069993',
    projectId: 'tyre-shop-1db0a',
    authDomain: 'tyre-shop-1db0a.firebaseapp.com',
    storageBucket: 'tyre-shop-1db0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4wPbcrSGtUULDdsupYOFL9OfXZcyClbo',
    appId: '1:551111069993:android:e38c3b09031f2e9b9d6738',
    messagingSenderId: '551111069993',
    projectId: 'tyre-shop-1db0a',
    storageBucket: 'tyre-shop-1db0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBptq2sRRJGQcmfTfGtcP_p-rzoIIt1YL4',
    appId: '1:551111069993:ios:eec265ac20e125299d6738',
    messagingSenderId: '551111069993',
    projectId: 'tyre-shop-1db0a',
    storageBucket: 'tyre-shop-1db0a.firebasestorage.app',
    iosBundleId: 'com.example.tyreShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBptq2sRRJGQcmfTfGtcP_p-rzoIIt1YL4',
    appId: '1:551111069993:ios:eec265ac20e125299d6738',
    messagingSenderId: '551111069993',
    projectId: 'tyre-shop-1db0a',
    storageBucket: 'tyre-shop-1db0a.firebasestorage.app',
    iosBundleId: 'com.example.tyreShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS_itfz9TO4HOXe7L64zk5058atnUx7UQ',
    appId: '1:551111069993:web:be4746d545a9d3d89d6738',
    messagingSenderId: '551111069993',
    projectId: 'tyre-shop-1db0a',
    authDomain: 'tyre-shop-1db0a.firebaseapp.com',
    storageBucket: 'tyre-shop-1db0a.firebasestorage.app',
  );

}